### ISSUE TITLE
Pinging fails with LibOpingError

### ISSUE THREAD

**Issue by vbrandl** [cfallin/rust-oping#9]
Every ping seems to fail with the following error: `oping::PingError::LibOpingError: Operation not permitted`.
I tried running rustping from this repository using `cargo run -- 127.0.0.1` and got the above error.
I tried both rust stable (`cargo 0.25.0 (8c93e0895 2018-02-01)`) and rust nightly (`cargo 0.26.0-nightly (1d6dfea44 2018-01-26)`).

Edit: after running `sudo setcap cap_net_raw+ep target/debug/rustping` it works

**Comment by cfallin** [comment]
Yes, liboping requires either a capability to send raw packets or to be run as root. It appears that e.g. `/usr/bin/ping` has the raw-packet capability too, at least on my system. The Linux kernel works this way for security reasons -- otherwise an unprivileged program could send an arbitrarily-crafted packet.

I'll add a note to `README.md` to this effect -- sorry, I should have documented it. Thanks!
